spring:
  datasource:
    url: 'jdbc:h2:~/rlc'
    username: 'rlc'
    password: ''
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'

jwt:
  secretKey: "rlc_596D9E46BAF2AE5B9BA893DE7282E"
  validTokenDay: 30
  validTokenTime: 60

feign:
  client:
    config:
      default:
        connectTimeout: 3000
        readTimeout: 3000

import:
  key: "key"
  secret: "secret"
